title: Google Glass EE2 Auto Importer
description: >-
  Utility for Mac users to import images from now-deprecated support of
  Google Glass Enterprise Edition 2 — and the story of how it came to be.
theme: minima

markdown: kramdown
